### ISSUE TITLE
Chime SDK currently doesnt render H.264 videos on certain Android mobile browsers

### ISSUE THREAD

**Issue by vidya-mohan** [aws/amazon-chime-sdk-js#299]
Video doesn't render for web applications build on the Chime JS on certain mobile devices such as Huawei. We see a slate such as the following:

![image](https://user-images.githubusercontent.com/55210968/80040600-4893a400-84af-11ea-8872-9f2f067f256e.png)

At present we are currently not supporting a website built with Amazon Chime SDK for JavaScript on a mobile browser (https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers has the list of browsers officially supported) though that is something on our roadmap.

Chime uses H.264 for video encoding and decoding to achieve hardware acceleration for better video performance. There are some devices which do not natively support H.264 because of licensing. Currently devices with Qualcom chipset with Android API higher than Kitkat Version 19 or Exynos chipset with Android API level higher than Lollipop Version 21 support it.

We have exposed an API that will help you detect it in the interim (https://github.com/aws/amazon-chime-sdk-js/issues/289). Chime SDK has an Android and also has the same rendering issue (https://github.com/aws/amazon-chime-sdk-android/issues/9).

**Comment by gsig123** [comment]
Hi! 

It seems like this issue has been resolved for the android-sdk (https://github.com/aws/amazon-chime-sdk-android/issues/9). 

Are you planning on doing something similar here  in the near future?

**Comment by robsondouglas** [comment]
I'm testing on my wife cellphone(Samsung J7) and saw this differences between portrait and landscape format:
![IMG_20200508_195808316](https://user-images.githubusercontent.com/13475100/81462112-8fa7b780-9186-11ea-9b65-acab6308a86c.jpg)

**Comment by robsondouglas** [comment]
![IMG_20200508_195821634](https://user-images.githubusercontent.com/13475100/81462148-c4b40a00-9186-11ea-8140-d326a0873249.jpg)
Landscape format

**Comment by yixial-amzn** [comment]
@robsondouglas Let us know if you still see this issue. We fixed a similar issue a while ago.

**Comment by yixial-amzn** [comment]
@vidya-mohan Could you please retry chrome browser on your Huawei phone? We recently made 
 fixes to allow phones w/o H.264 h/w support to still receive H.264. Thank you.

**Comment by yixial-amzn** [comment]
Please let us know if you still have issue. Thank you.
