### ISSUE TITLE
Huawei devices show a "update your client to support recent video improvements"

### ISSUE THREAD

**Issue by peternijssen** [aws/amazon-chime-sdk-js#519]
Related issues:
https://github.com/aws/amazon-chime-sdk-js/issues/289
https://github.com/aws/amazon-chime-sdk-js/issues/299
https://github.com/aws/amazon-chime-sdk-js/issues/276

Since the issues describe we should report a new issue, here it is. If more information is needed, let me know as I have a device next to me which I can reproduce it on.

**Meeting and attendee IDs:**
See attached logs

Chime Meeting ID: 85b05ea5-b188-4eaf-ad9e-b82b0524fc4b

OSX Attendee ID: 5f0435d4-b01c-47ac-bd9c-b1caeffb3127
Huawei Attendee ID: e010fe2c-7db4-41ba-b2c9-76259d821ba8

**Timeline**
See attached logs. I performed everything in less then 1 minute.

**Describe the bug**
I have multiple Huawei devices, when they join a meeting with the Amazon SDK,  they get the message "update your client to support recent video improvements". See attached issues for similar screenshots.

So far I've been able to work around it, in the following way;

- Person A opens the meeting on any device with video on
- Person B uses a Huawei phone and joins the meeting with video on
- Person B will see the "update your client to support recent video improvements"
- Person B disables his video.
- Person B enables his video.
- Person A disables his video.
- Person A enables his video.
- Person B no longer sees the message.

In between Person B also gets disconnected from the meeting and automatically reconnects.

**Platform**
The logs are produced with:
browser: Chrome Mobile 83.0.4103
device: LYA-L29
device.family: Huawei LYA-L29
os: Android 10
Chime SDK: 1.9.0

Also have reports from the following devices:
browser: Chrome Mobile 83.0.4103
device: CLT-L29
device.family: Huawei CLT-L29
os: Android 8.1.0
Chime SDK: 1.9.0

browser: Chrome Mobile 83.0.4103
device: POT-LX1
device.family: Huawei POT-LX1
os: Android 10
Chime SDK: 1.9.0

[huawei.txt](https://github.com/aws/amazon-chime-sdk-js/files/4838123/huawei.txt)
[osx.txt](https://github.com/aws/amazon-chime-sdk-js/files/4838124/osx.txt)

**Comment by yixial-amzn** [comment]
Is this using js-sdk demo browser? 
If yes, please select  Optional Feature>"Enable Simulcast For Chrome" in Option for Huawei phone.
If not, then the app needs to set this line to true:
https://github.com/aws/amazon-chime-sdk-js/blob/master/src/meetingsession/MeetingSessionConfiguration.ts#L74
 enableUnifiedPlanForChromiumBasedBrowsers: boolean = true;

**Comment by peternijssen** [comment]
This is our own implementation. I'll forward it to the team and let you know the outcome.

**Comment by johanderuijter** [comment]
It appears that setting `enableUnifiedPlanForChromiumBasedBrowsers` to `true` does resolve the Huawei issue describe in the initial post. However, it does introduce another issue in case of regular chrome that does not happen when plan-b instead of unified-plan is used.

When the unified-plan is used AND video is started immediately instead of by a manual action, the following error occurs (see full logs in the attached files below):
```
2020-06-30T14:17:59.114Z [INFO] SDK - received track event: kind=video id=c789106e-0c85-4b7c-b144-dc611b95726f label=c789106e-0c85-4b7c-b144-dc611b95726f
CreatePeerConnectionTask.ts:202 Uncaught TypeError: Cannot read property 'id' of undefined
    at CreatePeerConnectionTask.addRemoteVideoTrack (CreatePeerConnectionTask.ts:202)
    at RTCPeerConnection.CreatePeerConnectionTask._this.trackAddedHandler (CreatePeerConnectionTask.ts:96)
CreatePeerConnectionTask.addRemoteVideoTrack @ CreatePeerConnectionTask.ts:202
CreatePeerConnectionTask._this.trackAddedHandler @ CreatePeerConnectionTask.ts:96
```

Tracing the error back, it looks like the errors comes from this line in the code: https://github.com/aws/amazon-chime-sdk-js/blob/fe48254e6b7e5df3052c7c0bda98f649396db80b/src/task/CreatePeerConnectionTask.ts#L153-L154

It looks like the `stream: MediaStream` passed to the `addRemoteVideoTrack` is undefined with `steam` coming from the RTCTrackEvent in https://github.com/aws/amazon-chime-sdk-js/blob/fe48254e6b7e5df3052c7c0bda98f649396db80b/src/task/CreatePeerConnectionTask.ts#L126-L131

I checked by loggin some additional information locally, and it appears that `event.streams` is an empty array.

This appears to be a similar error as described in https://github.com/aws/amazon-chime-sdk-js/issues/479

[planb.txt](https://github.com/aws/amazon-chime-sdk-js/files/4852492/planb.txt)
[unified.txt](https://github.com/aws/amazon-chime-sdk-js/files/4852493/unified.txt)

**Comment by dashawk** [comment]
This is actually related to my issue #479  and yes @johanderuijter the `event.streams` becomes an empty array.

So as long as we have the stream, we can do something. But in case where there is no available stream, we should not do anything, and this way we can avoid that error.

Her in `/task/CreatePeerConnectionTask.ts` file, I modified the code from `line 127`.

### From
```javascript
const stream: MediaStream = event.streams[0]; 
 if (track.kind === 'audio') { 
   this.context.audioMixController.bindAudioStream(stream); 
 } else if (track.kind === 'video' && !this.trackIsVideoInput(track)) { 
   this.addRemoteVideoTrack(track, stream); 
 } 
```

### To
```javascript
const stream: MediaStream = event.streams[0]; 
if (stream) {
  if (track.kind === 'audio') { 
    this.context.audioMixController.bindAudioStream(stream); 
  } else if (track.kind === 'video' && !this.trackIsVideoInput(track)) { 
    this.addRemoteVideoTrack(track, stream); 
  }
}
```

This makes a lot of sense because we want to do something with the stream if it is available for us.

Hope this could be included in the next release.

**Comment by yixial-amzn** [comment]
@johanderuijter  Does adding stream check as suggested by @dashawk above resolve your issue? Thanks.

**Comment by johanderuijter** [comment]
If anything, it hides the error? but since that code is part of the sdk, i could only test in locally on a mac and have no idea what it might do on different devices? Also, that means we are essentially ignoring an incoming RTCTrackEvent, what does that mean for the rest of the session?

**Comment by alochbau-amzn** [comment]
As I just mentioned in https://github.com/aws/amazon-chime-sdk-js/issues/479

It is safe to ignore this error for now.

The TrackEvent is firing after the first WebRTC Offer/Answer due to a Transceiver being automatically created based on the local tile existing which sets a SDP option flag. The stream is being created shortly after and the TrackEvent will fire again and trigger the correct behavior.

I am working on adjusting the logic so that this TrackEvent does not fire without a Stream.

**Comment by johanderuijter** [comment]
Sounds good to me. We'll ignore the error for now.

@peternijssen I think that means that this issue is resolved as with this flag the huawei devices started working, can you confirm?

**Comment by peternijssen** [comment]
Yes. Issue resolved. 

Would be great to see the error resolved because that stops flooding our logs :)

**Comment by koushikAsl** [comment]
Hi,

I am getting this issue on my Huawei MediaPad M5 Lite, I am using Google Chrome v85.0.4183.101.
I am using v1.17.2 of the AWS-chime-SDK-js.
I have already tried with `enableUnifiedPlanForChromiumBasedBrowsers` to `true` but still not working

Any advice would be much appreciated.


![image](https://user-images.githubusercontent.com/71490414/93574234-d1a6fc80-f9b5-11ea-8fbc-f7974f3fc985.png)

Thanks,
Koushik

**Comment by yixial-amzn** [comment]
@koushikAsl Thank you for reporting the issue. The above image indicates the device does not support H.264 decoding. 

Could you please provide fo\lowing information? Thank you. 
1) Huawei client log
2) screenshot of meeting (with meeting-id and attendee-id  on top of the screen)
